---
name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - run: flutter pub get
      - run: flutter format --set-exit-if-changed .
      - run: flutter analyze .

  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - run: sudo apt-get update && sudo apt-get install clang cmake ninja-build pkg-config libgtk-3-dev libjsoncpp-dev
      - run: flutter config --enable-linux-desktop
      - run: flutter pub get
      - run: flutter doctor -v
      - run: flutter build -v linux --debug

  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "zulu"
      - uses: subosito/flutter-action@v1
      - run: flutter pub get
      - run: flutter doctor -v
      - run: flutter build -v apk --debug
